language: elixir
elixir:
  - 1.4.1
  - 1.5.0
  - 1.6.0
otp_release:
  - 19.2
  - 20.0
  - 20.1
matrix:
  exclude:
    - elixir: 1.4.1
      otp_release: 20.0
    - elixir: 1.4.1
      otp_release: 20.1
env:
  global:
    - MIX_ENV=test
before_install:
  - git submodule update --init --recursive
script:
  - "yes | mix do deps.get, deps.compile, compile, coveralls.travis"
